name: flowclear
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - greenlet=3.2.4=py311hf719da1_1
  - icu=75.1=hfee45f7_0
  - libcxx=21.1.2=hf598326_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.3=h5503f6c_1
  - pip=25.2=pyh8b19718_0
  - python=3.11.13=hc22306f_0_cpython
  - python_abi=3.11=8_cp311
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - sqlalchemy=2.0.43=py311h3696347_0
  - tk=8.6.13=h892fb3f_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - audioread==3.0.1
      - bcrypt==5.0.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - decorator==5.2.1
      - dnspython==2.8.0
      - ecdsa==0.19.1
      - email-validator==2.3.0
      - fastapi==0.116.2
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - h11==0.16.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - kss==2.5.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - matplotlib==3.10.7
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - networkx==3.5
      - numba==0.61.2
      - numpy==2.2.6
      - openai-whisper==20250625
      - packaging==25.0
      - pillow==12.0.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - psycopg2-binary==2.9.10
      - pyasn1==0.6.1
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pyjwt==2.10.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-jose==3.5.0
      - python-multipart==0.0.20
      - regex==2025.9.1
      - requests==2.32.5
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.16.1
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - starlette==0.48.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - torch==2.8.0
      - tqdm==4.67.1
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - uvicorn==0.35.0
prefix: /Users/unreasonable/miniforge3/envs/flowclear
